namespace: vyatta
name: vyos
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  ansible.netcommon: '>=1.0'
repository: git@github.com:ansible-collection-migration/vyatta.vyos.git
documentation: https://github.com/ansible-collection-migration/vyatta.vyos/tree/master/docs
homepage: https://github.com/ansible-collection-migration/vyatta.vyos
issues: https://github.com/ansible-collection-migration/vyatta.vyos/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
